#### Dataframes in Depth This is continuation of Working with Dataframes file

In [1]:
import numpy as np
import pandas as pd

In [2]:
pd.__version__

'2.3.3'

In [5]:
data_url = "https://andybek.com/pandas-soccer"

In [6]:
pd.read_csv(data_url)

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
0,Alexis Sanchez,Arsenal,28,LW,1,65.0,4329,12.0,17.10%,264,3,Chile,0,4,1,1,0
1,Mesut Ozil,Arsenal,28,AM,1,50.0,4395,9.5,5.60%,167,2,Germany,0,4,1,1,0
2,Petr Cech,Arsenal,35,GK,4,7.0,1529,5.5,5.90%,134,2,Czech Republic,0,6,1,1,0
3,Theo Walcott,Arsenal,28,RW,1,20.0,2393,7.5,1.50%,122,1,England,0,4,1,1,0
4,Laurent Koscielny,Arsenal,31,CB,3,22.0,912,6.0,0.70%,121,2,France,0,4,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
460,Edimilson Fernandes,West+Ham,21,CM,2,5.0,288,4.5,0.40%,38,2,Switzerland,0,1,20,0,1
461,Arthur Masuaku,West+Ham,23,LB,3,7.0,199,4.5,0.20%,34,4,Congo DR,0,2,20,0,1
462,Sam Byram,West+Ham,23,RB,3,4.5,198,4.5,0.30%,29,1,England,0,2,20,0,0
463,Ashley Fletcher,West+Ham,21,CF,1,1.0,412,4.5,5.90%,16,1,England,0,1,20,0,1
464,Diafra Sakho,West+Ham,27,CF,1,10.0,214,5.5,0.10%,12,4,Senegal,0,3,20,0,0

In [7]:
players = pd.read_csv(data_url)

In [8]:
players.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 465 entries, 0 to 464
Data columns (total 17 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   name          465 non-null    object
 1   club          465 non-null    object
 2   age           465 non-null    int64
 3   position      464 non-null    object
 4   position_cat  465 non-null    int64
 5   market_value  462 non-null    float64
 6   page_views    465 non-null    int64
 7   fpl_value     465 non-null    float64
 8   fpl_sel       465 non-null    object
 9   fpl_points    465 non-null    int64
 10  region        465 non-null    int64
 11  nationality   465 non-null    object
 12  new_foreign   465 non-null    int64
 13  age_cat       465 non-null    int64
 14  club_id       465 non-null    int64
 15  big_club      465 non-null    int64
 16  new_signing   465 non-null    int64
dtypes: float64(2), int64(10), object(5)
memory usage: 61.9+ KB

In [11]:
players.dtypes.value_counts()

int64      10
object      5
float64     2
Name: count, dtype: int64

In [13]:
players.head(3)

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
0,Alexis Sanchez,Arsenal,28,LW,1,65.0,4329,12.0,17.10%,264,3,Chile,0,4,1,1,0
1,Mesut Ozil,Arsenal,28,AM,1,50.0,4395,9.5,5.60%,167,2,Germany,0,4,1,1,0
2,Petr Cech,Arsenal,35,GK,4,7.0,1529,5.5,5.90%,134,2,Czech Republic,0,6,1,1,0

In [17]:
# What are the players having market value exceeding 40M?
p = players.market_value > 40  # This is returning a series

In [24]:
players[p].shape

(13, 17)

In [25]:
players.head(3)

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
0,Alexis Sanchez,Arsenal,28,LW,1,65.0,4329,12.0,17.10%,264,3,Chile,0,4,1,1,0
1,Mesut Ozil,Arsenal,28,AM,1,50.0,4395,9.5,5.60%,167,2,Germany,0,4,1,1,0
2,Petr Cech,Arsenal,35,GK,4,7.0,1529,5.5,5.90%,134,2,Czech Republic,0,6,1,1,0

In [27]:
players.position.unique()

array(['LW', 'AM', 'GK', 'RW', 'CB', 'RB', 'CF', 'LB', 'DM', 'RM', 'CM',
       nan, 'SS', 'LM'], dtype=object)

In [28]:
players.position.isin(['CB','LB','RB'])

0      False
1      False
2      False
3      False
4       True
       ...
460    False
461     True
462     True
463    False
464    False
Name: position, Length: 465, dtype: bool

In [31]:
players.loc[players.position.isin(['CB','RB','LB'])]

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
4,Laurent Koscielny,Arsenal,31,CB,3,22.0,912,6.0,0.70%,121,2,France,0,4,1,1,0
5,Hector Bellerin,Arsenal,22,RB,3,30.0,1675,6.0,13.70%,119,2,Spain,0,2,1,1,0
7,Nacho Monreal,Arsenal,31,LB,3,13.0,555,5.5,4.70%,115,2,Spain,0,4,1,1,0
8,Shkodran Mustafi,Arsenal,25,CB,3,30.0,1877,5.5,4.00%,90,2,Germany,0,3,1,1,1
17,Gabriel Paulista,Arsenal,26,CB,3,13.0,552,5.0,0.10%,45,3,Brazil,0,3,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
455,Aaron Cresswell,West+Ham,27,LB,3,12.0,380,5.0,1.30%,60,1,England,0,3,20,0,0
458,Angelo Ogbonna,West+Ham,29,CB,3,9.0,247,4.5,1.10%,45,2,Italy,0,4,20,0,0
459,Pablo Zabaleta,West+Ham,32,RB,3,7.0,698,5.0,2.70%,45,3,Argentina,0,5,20,0,0
461,Arthur Masuaku,West+Ham,23,LB,3,7.0,199,4.5,0.20%,34,4,Congo DR,0,2,20,0,1
462,Sam Byram,West+Ham,23,RB,3,4.5,198,4.5,0.30%,29,1,England,0,2,20,0,0

In [35]:
players.market_value.between(40,50,inclusive='neither')

0      False
1      False
2      False
3      False
4      False
       ...
460    False
461    False
462    False
463    False
464    False
Name: market_value, Length: 465, dtype: bool

In [36]:
players[players.market_value.between(40,50,inclusive='neither')]

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
218,Philippe Coutinho,Liverpool,25,AM,1,45.0,2958,9.0,30.80%,171,3,Brazil,0,3,10,1,0
246,Raheem Sterling,Manchester+City,22,LW,1,45.0,2074,8.0,3.80%,149,1,England,0,2,11,1,0
380,Dele Alli,Tottenham,21,CM,2,45.0,4626,9.5,38.60%,225,1,England,0,1,17,1,0

In [40]:
players[players.age <= 25]

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
5,Hector Bellerin,Arsenal,22,RB,3,30.0,1675,6.0,13.70%,119,2,Spain,0,2,1,1,0
8,Shkodran Mustafi,Arsenal,25,CB,3,30.0,1877,5.5,4.00%,90,2,Germany,0,3,1,1,1
9,Alex Iwobi,Arsenal,21,LW,1,10.0,1812,5.5,1.00%,89,4,Nigeria,0,1,1,1,0
10,Granit Xhaka,Arsenal,24,DM,2,35.0,1815,5.5,2.00%,85,2,Switzerland,0,2,1,1,0
11,Granit Xhaka,Arsenal,24,DM,2,35.0,1815,5.5,2.00%,85,2,Switzerland,0,2,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
456,Pedro Obiang,West+Ham,25,CM,2,9.0,286,4.5,0.30%,55,2,Spain,0,3,20,0,0
460,Edimilson Fernandes,West+Ham,21,CM,2,5.0,288,4.5,0.40%,38,2,Switzerland,0,1,20,0,1
461,Arthur Masuaku,West+Ham,23,LB,3,7.0,199,4.5,0.20%,34,4,Congo DR,0,2,20,0,1
462,Sam Byram,West+Ham,23,RB,3,4.5,198,4.5,0.30%,29,1,England,0,2,20,0,0
463,Ashley Fletcher,West+Ham,21,CF,1,1.0,412,4.5,5.90%,16,1,England,0,1,20,0,1

In [41]:
players.position.head(3)

0    LW
1    AM
2    GK
Name: position, dtype: object

In [43]:
# select all LB players
players[players.position =='LB']

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
7,Nacho Monreal,Arsenal,31,LB,3,13.00,555,5.5,4.70%,115,2,Spain,0,4,1,1,0
18,Kieran Gibbs,Arsenal,27,LB,3,10.00,489,5.0,0.50%,45,1,England,0,3,1,1,0
29,Sead Kolasinac,Arsenal,24,LB,3,15.00,618,6.0,6.90%,0,2,Bosnia,1,2,1,1,0
34,Charlie Daniels,Bournemouth,30,LB,3,3.00,185,5.0,19.80%,134,1,England,0,4,2,0,0
54,Brad Smith,Bournemouth,23,LB,3,2.00,297,4.0,3.30%,4,4,Australia,0,2,2,0,0
62,Gaetan Bong,Brighton+and+Hove,29,LB,3,1.50,97,4.5,0.20%,0,4,Cameroon,0,4,3,0,0
65,Markus Suttner,Brighton+and+Hove,30,LB,3,2.00,23,4.5,0.20%,0,2,Austria,0,4,3,0,0
82,Stephen Ward,Burnley,31,LB,3,1.50,152,4.5,2.50%,91,2,Ireland,0,4,4,0,0
99,Marcos Alonso Mendoza,Chelsea,26,LB,3,25.00,3069,7.0,12.40%,177,2,Spain,0,3,5,1,1
112,Kenedy,Chelsea,21,LB,3,7.00,566,5.0,0.10%,3,3,Brazil,0,1,5,1,0
119,Patrick van Aanholt,Crystal+Palace,26,LB,3,9.00,524,5.5,4.20%,98,2,Netherlands,0,3,6,0,0
128,Jeffrey Schlupp,Crystal+Palace,24,LB,3,8.00,385,5.0,0.30%,47,4,Ghana,0,2,6,0,0
134,Pape Souare,Crystal+Palace,27,LB,3,6.00,186,4.5,0.00%,6,4,Senegal,0,3,6,0,0
138,Leighton Baines,Everton,32,LB,3,12.00,491,6.0,10.00%,135,1,England,0,5,7,0,0
168,Chris Lowe,Huddersfield,28,LB,3,1.50,84,4.5,0.70%,0,2,Germany,0,4,8,0,0
175,Scott Malone,Huddersfield,26,LB,3,0.75,81,4.5,0.10%,0,1,England,0,3,8,0,0
196,Christian Fuchs,Leicester+City,31,LB,3,6.00,417,5.0,3.50%,104,2,Austria,0,4,9,0,0
212,Ben Chilwell,Leicester+City,20,LB,3,2.50,288,4.5,0.80%,19,1,England,0,1,9,0,0
236,Alberto Moreno,Liverpool,25,LB,3,10.00,397,4.5,0.30%,8,2,Spain,0,3,10,1,0
251,Aleksandar Kolarov,Manchester+City,31,LB,3,10.00,633,5.5,1.10%,95,2,Serbia,0,4,11,1,0
270,Daley Blind,Manchester+United,27,LB,3,22.00,867,5.5,1.20%,98,2,Netherlands,0,3,12,1,0
281,Luke Shaw,Manchester+United,22,LB,3,20.00,947,5.0,0.40%,45,1,England,0,2,12,1,0
294,Paul Dummett,Newcastle+United,25,LB,3,3.50,177,4.5,1.00%,0,2,Wales,0,3,13,0,0
298,Massadio Haidara,Newcastle+United,24,LB,3,1.50,114,4.0,0.50%,0,2,France,0,2,13,0,0
312,Ryan Bertrand,Southampton,27,LB,3,20.00,578,5.5,11.20%,123,1,England,0,3,14,0,0
328,Matt Targett,Southampton,21,LB,3,3.00,110,4.5,0.20%,12,1,England,0,1,14,0,0
336,Erik Pieters,Stoke+City,28,LB,3,7.00,134,5.0,1.30%,103,2,Netherlands,0,4,15,0,0
354,Josh Tymon,Stoke+City,18,LB,3,1.00,120,4.5,0.10%,9,1,England,0,1,15,0,0
363,Martin Olsson,Swansea,29,LB,3,5.00,458,5.0,0.30%,52,2,Sweden,0,4,16,0,0
369,Stephen Kingsley,Swansea,22,LB,3,0.75,168,4.5,0.20%,29,2,Scotland,0,2,16,0,0
389,Ben Davies,Tottenham,24,LB,3,12.00,396,5.5,1.80%,90,2,Wales,0,2,17,1,0
390,Danny Rose,Tottenham,27,LB,3,28.00,848,6.5,0.60%,84,1,England,0,3,17,1,0
403,Jose Holebas,Watford,33,LB,3,2.00,345,5.0,0.60%,87,2,Greece,0,5,18,0,0
455,Aaron Cresswell,West+Ham,27,LB,3,12.00,380,5.0,1.30%,60,1,England,0,3,20,0,0
461,Arthur Masuaku,West+Ham,23,LB,3,7.00,199,4.5,0.20%,34,4,Congo DR,0,2,20,0,1

In [49]:
players[(players.position == "LB") & (players.age>=25)]

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
7,Nacho Monreal,Arsenal,31,LB,3,13.00,555,5.5,4.70%,115,2,Spain,0,4,1,1,0
18,Kieran Gibbs,Arsenal,27,LB,3,10.00,489,5.0,0.50%,45,1,England,0,3,1,1,0
34,Charlie Daniels,Bournemouth,30,LB,3,3.00,185,5.0,19.80%,134,1,England,0,4,2,0,0
62,Gaetan Bong,Brighton+and+Hove,29,LB,3,1.50,97,4.5,0.20%,0,4,Cameroon,0,4,3,0,0
65,Markus Suttner,Brighton+and+Hove,30,LB,3,2.00,23,4.5,0.20%,0,2,Austria,0,4,3,0,0
82,Stephen Ward,Burnley,31,LB,3,1.50,152,4.5,2.50%,91,2,Ireland,0,4,4,0,0
99,Marcos Alonso Mendoza,Chelsea,26,LB,3,25.00,3069,7.0,12.40%,177,2,Spain,0,3,5,1,1
119,Patrick van Aanholt,Crystal+Palace,26,LB,3,9.00,524,5.5,4.20%,98,2,Netherlands,0,3,6,0,0
134,Pape Souare,Crystal+Palace,27,LB,3,6.00,186,4.5,0.00%,6,4,Senegal,0,3,6,0,0
138,Leighton Baines,Everton,32,LB,3,12.00,491,6.0,10.00%,135,1,England,0,5,7,0,0
168,Chris Lowe,Huddersfield,28,LB,3,1.50,84,4.5,0.70%,0,2,Germany,0,4,8,0,0
175,Scott Malone,Huddersfield,26,LB,3,0.75,81,4.5,0.10%,0,1,England,0,3,8,0,0
196,Christian Fuchs,Leicester+City,31,LB,3,6.00,417,5.0,3.50%,104,2,Austria,0,4,9,0,0
236,Alberto Moreno,Liverpool,25,LB,3,10.00,397,4.5,0.30%,8,2,Spain,0,3,10,1,0
251,Aleksandar Kolarov,Manchester+City,31,LB,3,10.00,633,5.5,1.10%,95,2,Serbia,0,4,11,1,0
270,Daley Blind,Manchester+United,27,LB,3,22.00,867,5.5,1.20%,98,2,Netherlands,0,3,12,1,0
294,Paul Dummett,Newcastle+United,25,LB,3,3.50,177,4.5,1.00%,0,2,Wales,0,3,13,0,0
312,Ryan Bertrand,Southampton,27,LB,3,20.00,578,5.5,11.20%,123,1,England,0,3,14,0,0
336,Erik Pieters,Stoke+City,28,LB,3,7.00,134,5.0,1.30%,103,2,Netherlands,0,4,15,0,0
363,Martin Olsson,Swansea,29,LB,3,5.00,458,5.0,0.30%,52,2,Sweden,0,4,16,0,0
390,Danny Rose,Tottenham,27,LB,3,28.00,848,6.5,0.60%,84,1,England,0,3,17,1,0
403,Jose Holebas,Watford,33,LB,3,2.00,345,5.0,0.60%,87,2,Greece,0,5,18,0,0
455,Aaron Cresswell,West+Ham,27,LB,3,12.00,380,5.0,1.30%,60,1,England,0,3,20,0,0

In [52]:
# find out players who have market value 10+ and age is less than 25 and position is LB
players[(players.position == 'LB') & (players.age<=25) & (players.market_value >=10)]

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
29,Sead Kolasinac,Arsenal,24,LB,3,15.0,618,6.0,6.90%,0,2,Bosnia,1,2,1,1,0
236,Alberto Moreno,Liverpool,25,LB,3,10.0,397,4.5,0.30%,8,2,Spain,0,3,10,1,0
281,Luke Shaw,Manchester+United,22,LB,3,20.0,947,5.0,0.40%,45,1,England,0,2,12,1,0
389,Ben Davies,Tottenham,24,LB,3,12.0,396,5.5,1.80%,90,2,Wales,0,2,17,1,0

In [58]:
# find out players who have market value 10+ and age is less than 25 and position is LB not from Arsenal club or Tottenham club
players[(players.position == 'LB') & (players.age<=25) & (players.market_value >=10) & (players.club != 'Arsenal') & (players.club != 'Tottenham')]  # without using ~ operator
players[(players.position == 'LB') & (players.age<=25) & (players.market_value >=10) & ~(players.club.isin(['Arsenal','Tottenham']))]  # using ~ operator ~ means except given data

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
236,Alberto Moreno,Liverpool,25,LB,3,10.0,397,4.5,0.30%,8,2,Spain,0,3,10,1,0
281,Luke Shaw,Manchester+United,22,LB,3,20.0,947,5.0,0.40%,45,1,England,0,2,12,1,0