#### What is dataframe

In [1]:
import pandas as pd

In [2]:
names = ["Tony","Bruce","Steve","Chris"]
age = [45,46,100,55]

In [3]:
df = pd.DataFrame({"Names":names,"Age":age})

In [4]:
df

   Names  Age
0   Tony   45
1  Bruce   46
2  Steve  100
3  Chris   55

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Names   4 non-null      object
 1   Age     4 non-null      int64
dtypes: int64(1), object(1)
memory usage: 196.0+ bytes

In [6]:
dataurl = 'https://andybek.com/pandas-nutrition'

In [7]:
nutrition = pd.read_csv(dataurl)

In [8]:
nutrition.sample(3)
# nutrition.head()

,Unnamed: 0,name,serving_size,calories,total_fat,saturated_fat,cholesterol,sodium,choline,folate,...,fat,saturated_fatty_acids,monounsaturated_fatty_acids,polyunsaturated_fatty_acids,fatty_acids_total_trans,alcohol,ash,caffeine,theobromine,water
4704,4704,"Turkey, roasted, meat only, from whole bird, back",100 g,173,6g,1.8g,128mg,104.00 mg,95.8 mg,9.00 mcg,...,6.04 g,1.807 g,2.061 g,1.662 g,128.00 mg,0.0 g,1.12 g,0.00 mg,0.00 mg,65.23 g
1202,1202,"Peas, raw, edible-podded",100 g,42,0.2g,NaN,0,4.00 mg,17.4 mg,42.00 mcg,...,0.20 g,0.039 g,0.021 g,0.089 g,0.00 mg,0.0 g,0.56 g,0.00 mg,0.00 mg,88.89 g
8127,8127,"Infant formula, not reconstituted, powder, wit...",100 g,510,27g,11g,0,180.00 mg,61.0 mg,80.00 mcg,...,27.00 g,11.370 g,10.320 g,5.200 g,0.00 mg,0.0 g,3.20 g,0.00 mg,0.00 mg,3.00 g

In [9]:
nutrition.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8789 entries, 0 to 8788
Data columns (total 77 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Unnamed: 0                   8789 non-null   int64
 1   name                         8789 non-null   object
 2   serving_size                 8789 non-null   object
 3   calories                     8789 non-null   int64
 4   total_fat                    8789 non-null   object
 5   saturated_fat                7199 non-null   object
 6   cholesterol                  8789 non-null   object
 7   sodium                       8789 non-null   object
 8   choline                      8789 non-null   object
 9   folate                       8789 non-null   object
 10  folic_acid                   8789 non-null   object
 11  niacin                       8789 non-null   object
 12  pantothenic_acid             8789 non-null   object
 13  riboflavin                   8789 non-null   object
 14  thiamin                      8789 non-null   object
 15  vitamin_a                    8789 non-null   object
 16  vitamin_a_rae                8789 non-null   object
 17  carotene_alpha               8789 non-null   object
 18  carotene_beta                8789 non-null   object
 19  cryptoxanthin_beta           8789 non-null   object
 20  lutein_zeaxanthin            8789 non-null   object
 21  lucopene                     8789 non-null   int64
 22  vitamin_b12                  8789 non-null   object
 23  vitamin_b6                   8789 non-null   object
 24  vitamin_c                    8789 non-null   object
 25  vitamin_d                    8789 non-null   object
 26  vitamin_e                    8789 non-null   object
 27  tocopherol_alpha             8789 non-null   object
 28  vitamin_k                    8789 non-null   object
 29  calcium                      8789 non-null   object
 30  copper                       8789 non-null   object
 31  irom                         8789 non-null   object
 32  magnesium                    8789 non-null   object
 33  manganese                    8789 non-null   object
 34  phosphorous                  8789 non-null   object
 35  potassium                    8789 non-null   object
 36  selenium                     8789 non-null   object
 37  zink                         8789 non-null   object
 38  protein                      8789 non-null   object
 39  alanine                      8789 non-null   object
 40  arginine                     8789 non-null   object
 41  aspartic_acid                8789 non-null   object
 42  cystine                      8789 non-null   object
 43  glutamic_acid                8789 non-null   object
 44  glycine                      8789 non-null   object
 45  histidine                    8789 non-null   object
 46  hydroxyproline               8789 non-null   object
 47  isoleucine                   8789 non-null   object
 48  leucine                      8789 non-null   object
 49  lysine                       8789 non-null   object
 50  methionine                   8789 non-null   object
 51  phenylalanine                8789 non-null   object
 52  proline                      8789 non-null   object
 53  serine                       8789 non-null   object
 54  threonine                    8789 non-null   object
 55  tryptophan                   8789 non-null   object
 56  tyrosine                     8789 non-null   object
 57  valine                       8789 non-null   object
 58  carbohydrate                 8789 non-null   object
 59  fiber                        8789 non-null   object
 60  sugars                       8789 non-null   object
 61  fructose                     8789 non-null   object
 62  galactose                    8789 non-null   object
 63  glucose                      8789 non-null   object
 64  lactose                      8789 non-null   object
 65  maltose                      8789 non-null   object
 66  sucrose                      8789 non-null   object
 67  fat                          8789 non-null   object
 68  saturated_fatty_acids        8789 non-null   object
 69  monounsaturated_fatty_acids  8789 non-null   object
 70  polyunsaturated_fatty_acids  8789 non-null   object
 71  fatty_acids_total_trans      8789 non-null   object
 72  alcohol                      8789 non-null   object
 73  ash                          8789 non-null   object
 74  caffeine                     8789 non-null   object
 75  theobromine                  8789 non-null   object
 76  water                        8789 non-null   object
dtypes: int64(3), object(74)
memory usage: 5.2+ MB

In [10]:
# dropping Unnamed:0 column as its extra
nutrition.drop('Unnamed: 0',axis=1)  # axis 1 stands for columns and axis 0 stands for rows

,name,serving_size,calories,total_fat,saturated_fat,cholesterol,sodium,choline,folate,folic_acid,...,fat,saturated_fatty_acids,monounsaturated_fatty_acids,polyunsaturated_fatty_acids,fatty_acids_total_trans,alcohol,ash,caffeine,theobromine,water
0,Cornstarch,100 g,381,0.1g,NaN,0,9.00 mg,0.4 mg,0.00 mcg,0.00 mcg,...,0.05 g,0.009 g,0.016 g,0.025 g,0.00 mg,0.0 g,0.09 g,0.00 mg,0.00 mg,8.32 g
1,"Nuts, pecans",100 g,691,72g,6.2g,0,0.00 mg,40.5 mg,22.00 mcg,0.00 mcg,...,71.97 g,6.180 g,40.801 g,21.614 g,0.00 mg,0.0 g,1.49 g,0.00 mg,0.00 mg,3.52 g
2,"Eggplant, raw",100 g,25,0.2g,NaN,0,2.00 mg,6.9 mg,22.00 mcg,0.00 mcg,...,0.18 g,0.034 g,0.016 g,0.076 g,0.00 mg,0.0 g,0.66 g,0.00 mg,0.00 mg,92.30 g
3,"Teff, uncooked",100 g,367,2.4g,0.4g,0,12.00 mg,13.1 mg,0,0,...,2.38 g,0.449 g,0.589 g,1.071 g,0,0,2.37 g,0,0,8.82 g
4,"Sherbet, orange",100 g,144,2g,1.2g,1mg,46.00 mg,7.7 mg,4.00 mcg,0.00 mcg,...,2.00 g,1.160 g,0.530 g,0.080 g,1.00 mg,0.0 g,0.40 g,0.00 mg,0.00 mg,66.10 g
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8784,"Beef, raw, all grades, trimmed to 0"" fat, sepa...",100 g,125,3.5g,1.4g,62mg,54.00 mg,64.5 mg,4.00 mcg,0.00 mcg,...,3.50 g,1.353 g,1.554 g,0.244 g,62.00 mg,0.0 g,1.11 g,0.00 mg,0.00 mg,72.51 g
8785,"Lamb, cooked, separable lean only, composite o...",100 g,206,8.9g,3.9g,109mg,50.00 mg,0,0.00 mcg,0.00 mcg,...,8.86 g,3.860 g,3.480 g,0.520 g,109.00 mg,0,1.60 g,0,0,59.95 g
8786,"Lamb, raw, separable lean and fat, composite o...",100 g,277,23g,12g,78mg,39.00 mg,0,1.00 mcg,0.00 mcg,...,22.74 g,11.570 g,8.720 g,0.980 g,78.00 mg,0,0.92 g,0,0,59.80 g
8787,"Beef, raw, all grades, trimmed to 0"" fat, sepa...",100 g,121,3g,1.1g,60mg,53.00 mg,64.2 mg,4.00 mcg,0.00 mcg,...,3.04 g,1.086 g,1.266 g,0.233 g,60.00 mg,0.0 g,1.10 g,0.00 mg,0.00 mg,73.43 g
8788,"Beef, raw, all grades, trimmed to 0"" fat, sepa...",100 g,121,3g,1.1g,60mg,53.00 mg,64.2 mg,4.00 mcg,0.00 mcg,...,3.04 g,1.086 g,1.266 g,0.233 g,60.00 mg,0.0 g,1.10 g,0.00 mg,0.00 mg,73.43 g

In [11]:
nutrition.head()

,Unnamed: 0,name,serving_size,calories,total_fat,saturated_fat,cholesterol,sodium,choline,folate,...,fat,saturated_fatty_acids,monounsaturated_fatty_acids,polyunsaturated_fatty_acids,fatty_acids_total_trans,alcohol,ash,caffeine,theobromine,water
0,0,Cornstarch,100 g,381,0.1g,NaN,0,9.00 mg,0.4 mg,0.00 mcg,...,0.05 g,0.009 g,0.016 g,0.025 g,0.00 mg,0.0 g,0.09 g,0.00 mg,0.00 mg,8.32 g
1,1,"Nuts, pecans",100 g,691,72g,6.2g,0,0.00 mg,40.5 mg,22.00 mcg,...,71.97 g,6.180 g,40.801 g,21.614 g,0.00 mg,0.0 g,1.49 g,0.00 mg,0.00 mg,3.52 g
2,2,"Eggplant, raw",100 g,25,0.2g,NaN,0,2.00 mg,6.9 mg,22.00 mcg,...,0.18 g,0.034 g,0.016 g,0.076 g,0.00 mg,0.0 g,0.66 g,0.00 mg,0.00 mg,92.30 g
3,3,"Teff, uncooked",100 g,367,2.4g,0.4g,0,12.00 mg,13.1 mg,0,...,2.38 g,0.449 g,0.589 g,1.071 g,0,0,2.37 g,0,0,8.82 g
4,4,"Sherbet, orange",100 g,144,2g,1.2g,1mg,46.00 mg,7.7 mg,4.00 mcg,...,2.00 g,1.160 g,0.530 g,0.080 g,1.00 mg,0.0 g,0.40 g,0.00 mg,0.00 mg,66.10 g

In [12]:
nutrition = pd.read_csv(dataurl, index_col=[0])  # here 0 is telling use column 0 as index while fetching data from dataurl

In [13]:
nutrition

,name,serving_size,calories,total_fat,saturated_fat,cholesterol,sodium,choline,folate,folic_acid,...,fat,saturated_fatty_acids,monounsaturated_fatty_acids,polyunsaturated_fatty_acids,fatty_acids_total_trans,alcohol,ash,caffeine,theobromine,water
0,Cornstarch,100 g,381,0.1g,NaN,0,9.00 mg,0.4 mg,0.00 mcg,0.00 mcg,...,0.05 g,0.009 g,0.016 g,0.025 g,0.00 mg,0.0 g,0.09 g,0.00 mg,0.00 mg,8.32 g
1,"Nuts, pecans",100 g,691,72g,6.2g,0,0.00 mg,40.5 mg,22.00 mcg,0.00 mcg,...,71.97 g,6.180 g,40.801 g,21.614 g,0.00 mg,0.0 g,1.49 g,0.00 mg,0.00 mg,3.52 g
2,"Eggplant, raw",100 g,25,0.2g,NaN,0,2.00 mg,6.9 mg,22.00 mcg,0.00 mcg,...,0.18 g,0.034 g,0.016 g,0.076 g,0.00 mg,0.0 g,0.66 g,0.00 mg,0.00 mg,92.30 g
3,"Teff, uncooked",100 g,367,2.4g,0.4g,0,12.00 mg,13.1 mg,0,0,...,2.38 g,0.449 g,0.589 g,1.071 g,0,0,2.37 g,0,0,8.82 g
4,"Sherbet, orange",100 g,144,2g,1.2g,1mg,46.00 mg,7.7 mg,4.00 mcg,0.00 mcg,...,2.00 g,1.160 g,0.530 g,0.080 g,1.00 mg,0.0 g,0.40 g,0.00 mg,0.00 mg,66.10 g
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8784,"Beef, raw, all grades, trimmed to 0"" fat, sepa...",100 g,125,3.5g,1.4g,62mg,54.00 mg,64.5 mg,4.00 mcg,0.00 mcg,...,3.50 g,1.353 g,1.554 g,0.244 g,62.00 mg,0.0 g,1.11 g,0.00 mg,0.00 mg,72.51 g
8785,"Lamb, cooked, separable lean only, composite o...",100 g,206,8.9g,3.9g,109mg,50.00 mg,0,0.00 mcg,0.00 mcg,...,8.86 g,3.860 g,3.480 g,0.520 g,109.00 mg,0,1.60 g,0,0,59.95 g
8786,"Lamb, raw, separable lean and fat, composite o...",100 g,277,23g,12g,78mg,39.00 mg,0,1.00 mcg,0.00 mcg,...,22.74 g,11.570 g,8.720 g,0.980 g,78.00 mg,0,0.92 g,0,0,59.80 g
8787,"Beef, raw, all grades, trimmed to 0"" fat, sepa...",100 g,121,3g,1.1g,60mg,53.00 mg,64.2 mg,4.00 mcg,0.00 mcg,...,3.04 g,1.086 g,1.266 g,0.233 g,60.00 mg,0.0 g,1.10 g,0.00 mg,0.00 mg,73.43 g
8788,"Beef, raw, all grades, trimmed to 0"" fat, sepa...",100 g,121,3g,1.1g,60mg,53.00 mg,64.2 mg,4.00 mcg,0.00 mcg,...,3.04 g,1.086 g,1.266 g,0.233 g,60.00 mg,0.0 g,1.10 g,0.00 mg,0.00 mg,73.43 g

In [14]:
nutrition.index

Index([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,
       ...
       8779, 8780, 8781, 8782, 8783, 8784, 8785, 8786, 8787, 8788],
      dtype='int64', length=8789)

In [15]:
nutrition = nutrition.set_index('name')

In [16]:
nutrition.head(8)

,serving_size,calories,total_fat,saturated_fat,cholesterol,sodium,choline,folate,folic_acid,niacin,...,fat,saturated_fatty_acids,monounsaturated_fatty_acids,polyunsaturated_fatty_acids,fatty_acids_total_trans,alcohol,ash,caffeine,theobromine,water
name,,,,,,,,,,,,,,,,,,,,,
Cornstarch,100 g,381,0.1g,NaN,0,9.00 mg,0.4 mg,0.00 mcg,0.00 mcg,0.000 mg,...,0.05 g,0.009 g,0.016 g,0.025 g,0.00 mg,0.0 g,0.09 g,0.00 mg,0.00 mg,8.32 g
"Nuts, pecans",100 g,691,72g,6.2g,0,0.00 mg,40.5 mg,22.00 mcg,0.00 mcg,1.167 mg,...,71.97 g,6.180 g,40.801 g,21.614 g,0.00 mg,0.0 g,1.49 g,0.00 mg,0.00 mg,3.52 g
"Eggplant, raw",100 g,25,0.2g,NaN,0,2.00 mg,6.9 mg,22.00 mcg,0.00 mcg,0.649 mg,...,0.18 g,0.034 g,0.016 g,0.076 g,0.00 mg,0.0 g,0.66 g,0.00 mg,0.00 mg,92.30 g
"Teff, uncooked",100 g,367,2.4g,0.4g,0,12.00 mg,13.1 mg,0,0,3.363 mg,...,2.38 g,0.449 g,0.589 g,1.071 g,0,0,2.37 g,0,0,8.82 g
"Sherbet, orange",100 g,144,2g,1.2g,1mg,46.00 mg,7.7 mg,4.00 mcg,0.00 mcg,0.063 mg,...,2.00 g,1.160 g,0.530 g,0.080 g,1.00 mg,0.0 g,0.40 g,0.00 mg,0.00 mg,66.10 g
"Cauliflower, raw",100 g,25,0.3g,0.1g,0,30.00 mg,44.3 mg,57.00 mcg,0.00 mcg,0.507 mg,...,0.28 g,0.130 g,0.034 g,0.031 g,0.00 mg,0.0 g,0.76 g,0.00 mg,0.00 mg,92.07 g
"Taro leaves, raw",100 g,42,0.7g,0.2g,0,3.00 mg,12.8 mg,126.00 mcg,0.00 mcg,1.513 mg,...,0.74 g,0.151 g,0.060 g,0.307 g,0.00 mg,0.0 g,1.92 g,0.00 mg,0.00 mg,85.66 g
"Lamb, raw, ground",100 g,282,23g,10g,73mg,59.00 mg,69.3 mg,18.00 mcg,0.00 mcg,5.960 mg,...,23.41 g,10.190 g,9.600 g,1.850 g,73.00 mg,0.0 g,0.87 g,0.00 mg,0.00 mg,59.47 g

In [17]:
nutrition.loc["Eggplant, raw"]

serving_size       100 g
calories              25
total_fat           0.2g
saturated_fat        NaN
cholesterol            0
                  ...
alcohol            0.0 g
ash               0.66 g
caffeine         0.00 mg
theobromine      0.00 mg
water            92.30 g
Name: Eggplant, raw, Length: 75, dtype: object

In [18]:
nutrition.loc["Cornstarch","calories"]  # df.loc[row,column]

np.int64(381)

In [19]:
nutrition.loc["Sherbet, orange":"Lamb, raw, ground","calories":"sodium"]  # df.loc[[row:row],[column:column]]

                   calories total_fat saturated_fat cholesterol    sodium
name
Sherbet, orange         144        2g          1.2g         1mg  46.00 mg
Cauliflower, raw         25      0.3g          0.1g           0  30.00 mg
Taro leaves, raw         42      0.7g          0.2g           0   3.00 mg
Lamb, raw, ground       282       23g           10g        73mg  59.00 mg

In [20]:
nutrition.iloc[5,7]  # df.iloc[row,column]

'57.00 mcg'

In [21]:
nutrition.iloc[[12,17,25],6:9]  # this is dataframe slicing iloc[[rows],columns slicing]

                       choline     folate folic_acid
name
Mango nectar, canned    1.5 mg   7.00 mcg   0.00 mcg
Peppers, raw, jalapeno  7.5 mg  27.00 mcg   0.00 mcg
PACE, Green Taco Sauce       0          0          0

In [22]:
nutrition.iloc[[10,20,30],[10,30,40]]  # this is dataframe slicing iloc[[rows],[columns]]

                       pantothenic_acid magnesium  cystine
name
PACE, Picante Sauce                   0         0        0
Grapes, raw, muscadine                0  14.00 mg        0
Pasta, unenriched, dry         0.431 mg  53.00 mg  0.255 g

In [23]:
nutrition.head(2)

,serving_size,calories,total_fat,saturated_fat,cholesterol,sodium,choline,folate,folic_acid,niacin,...,fat,saturated_fatty_acids,monounsaturated_fatty_acids,polyunsaturated_fatty_acids,fatty_acids_total_trans,alcohol,ash,caffeine,theobromine,water
name,,,,,,,,,,,,,,,,,,,,,
Cornstarch,100 g,381,0.1g,NaN,0,9.00 mg,0.4 mg,0.00 mcg,0.00 mcg,0.000 mg,...,0.05 g,0.009 g,0.016 g,0.025 g,0.00 mg,0.0 g,0.09 g,0.00 mg,0.00 mg,8.32 g
"Nuts, pecans",100 g,691,72g,6.2g,0,0.00 mg,40.5 mg,22.00 mcg,0.00 mcg,1.167 mg,...,71.97 g,6.180 g,40.801 g,21.614 g,0.00 mg,0.0 g,1.49 g,0.00 mg,0.00 mg,3.52 g

In [24]:
nutrition.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8789 entries, Cornstarch to Beef, raw, all grades, trimmed to 0" fat, separable lean only, boneless, eye of round steak, round
Data columns (total 75 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   serving_size                 8789 non-null   object
 1   calories                     8789 non-null   int64
 2   total_fat                    8789 non-null   object
 3   saturated_fat                7199 non-null   object
 4   cholesterol                  8789 non-null   object
 5   sodium                       8789 non-null   object
 6   choline                      8789 non-null   object
 7   folate                       8789 non-null   object
 8   folic_acid                   8789 non-null   object
 9   niacin                       8789 non-null   object
 10  pantothenic_acid             8789 non-null   object
 11  riboflavin                   8789 non-null   object
 12  thiamin                      8789 non-null   object
 13  vitamin_a                    8789 non-null   object
 14  vitamin_a_rae                8789 non-null   object
 15  carotene_alpha               8789 non-null   object
 16  carotene_beta                8789 non-null   object
 17  cryptoxanthin_beta           8789 non-null   object
 18  lutein_zeaxanthin            8789 non-null   object
 19  lucopene                     8789 non-null   int64
 20  vitamin_b12                  8789 non-null   object
 21  vitamin_b6                   8789 non-null   object
 22  vitamin_c                    8789 non-null   object
 23  vitamin_d                    8789 non-null   object
 24  vitamin_e                    8789 non-null   object
 25  tocopherol_alpha             8789 non-null   object
 26  vitamin_k                    8789 non-null   object
 27  calcium                      8789 non-null   object
 28  copper                       8789 non-null   object
 29  irom                         8789 non-null   object
 30  magnesium                    8789 non-null   object
 31  manganese                    8789 non-null   object
 32  phosphorous                  8789 non-null   object
 33  potassium                    8789 non-null   object
 34  selenium                     8789 non-null   object
 35  zink                         8789 non-null   object
 36  protein                      8789 non-null   object
 37  alanine                      8789 non-null   object
 38  arginine                     8789 non-null   object
 39  aspartic_acid                8789 non-null   object
 40  cystine                      8789 non-null   object
 41  glutamic_acid                8789 non-null   object
 42  glycine                      8789 non-null   object
 43  histidine                    8789 non-null   object
 44  hydroxyproline               8789 non-null   object
 45  isoleucine                   8789 non-null   object
 46  leucine                      8789 non-null   object
 47  lysine                       8789 non-null   object
 48  methionine                   8789 non-null   object
 49  phenylalanine                8789 non-null   object
 50  proline                      8789 non-null   object
 51  serine                       8789 non-null   object
 52  threonine                    8789 non-null   object
 53  tryptophan                   8789 non-null   object
 54  tyrosine                     8789 non-null   object
 55  valine                       8789 non-null   object
 56  carbohydrate                 8789 non-null   object
 57  fiber                        8789 non-null   object
 58  sugars                       8789 non-null   object
 59  fructose                     8789 non-null   object
 60  galactose                    8789 non-null   object
 61  glucose                      8789 non-null   object
 62  lactose                      8789 non-null   object
 63  maltose                      8789 non-null   object
 64  sucrose                      8789 non-null   object
 65  fat                          8789 non-null   object
 66  saturated_fatty_acids        8789 non-null   object
 67  monounsaturated_fatty_acids  8789 non-null   object
 68  polyunsaturated_fatty_acids  8789 non-null   object
 69  fatty_acids_total_trans      8789 non-null   object
 70  alcohol                      8789 non-null   object
 71  ash                          8789 non-null   object
 72  caffeine                     8789 non-null   object
 73  theobromine                  8789 non-null   object
 74  water                        8789 non-null   object
dtypes: int64(2), object(73)
memory usage: 5.3+ MB

### Skill Challenge

In [25]:
# Randomly select 10 food items and assign df to nutr_mini
nutr_mini = nutrition.sample(10)

In [26]:
nutr_mini

,serving_size,calories,total_fat,saturated_fat,cholesterol,sodium,choline,folate,folic_acid,niacin,...,fat,saturated_fatty_acids,monounsaturated_fatty_acids,polyunsaturated_fatty_acids,fatty_acids_total_trans,alcohol,ash,caffeine,theobromine,water
name,,,,,,,,,,,,,,,,,,,,,
"Desserts, prepared-from-recipe, apple crisp",100 g,161,3.4g,0.7g,0,351.00 mg,0,16.00 mcg,12.00 mcg,0.846 mg,...,3.43 g,0.685 g,1.334 g,1.144 g,0.00 mg,0.0 g,1.07 g,0.00 mg,0.00 mg,62.91 g
"Frankfurter, low fat, meat and poultry",100 g,121,2.8g,1g,44mg,983.00 mg,76.0 mg,3.00 mcg,0.00 mcg,3.160 mg,...,2.80 g,0.970 g,1.190 g,0.360 g,44.00 mg,0.0 g,3.40 g,0.00 mg,0.00 mg,69.90 g
"Whey, dried, acid",100 g,339,0.5g,0.3g,3mg,968.00 mg,225.0 mg,33.00 mcg,0.00 mcg,1.160 mg,...,0.54 g,0.342 g,0.149 g,0.021 g,3.00 mg,0.0 g,10.77 g,0.00 mg,0.00 mg,3.51 g
"Soybean, curd cheese",100 g,151,8.1g,1.2g,0,20.00 mg,62.5 mg,22.00 mcg,0.00 mcg,0.500 mg,...,8.10 g,1.172 g,1.789 g,4.572 g,0.00 mg,0.0 g,1.60 g,0.00 mg,0.00 mg,70.90 g
"Squash, without salt, boiled, cooked, frozen, butternut, winter",100 g,39,0.1g,NaN,0,2.00 mg,0,16.00 mcg,0.00 mcg,0.464 mg,...,0.07 g,0.014 g,0.005 g,0.029 g,0.00 mg,0,0.86 g,0,0,87.80 g
"Peas, raw, sprouted, mature seeds",100 g,124,0.7g,0.1g,0,20.00 mg,0,144.00 mcg,0.00 mcg,3.088 mg,...,0.68 g,0.124 g,0.061 g,0.326 g,0.00 mg,0,1.14 g,0,0,62.27 g
"Beverages, prepared with distilled water, brewed, black, tea",100 g,1,0g,NaN,0,0.00 mg,0,5.00 mcg,0.00 mcg,0.000 mg,...,0.00 g,0.002 g,0.001 g,0.004 g,0.00 mg,0,0.02 g,20.00 mg,0,99.70 g
"KASHI, Oatmeal Dark Chocolate Cookies, TLC",100 g,426,16g,4.2g,0,0,0,0,0,0,...,16.30 g,4.200 g,7.800 g,4.000 g,0.00 mg,0,0,0,0,8.00 g
"SPAGHETTIOS, SpaghettiOs with Meatballs",100 g,95,2.8g,1g,8mg,238.00 mg,0,24.00 mcg,0,1.190 mg,...,2.78 g,0.992 g,1.190 g,0.397 g,8.00 mg,0,2.06 g,0,0,78.10 g
"Snacks, unsalted, plain, potato chips",100 g,536,35g,11g,0,8.00 mg,37.5 mg,45.00 mcg,0.00 mcg,3.827 mg,...,34.60 g,10.960 g,9.840 g,12.170 g,0.00 mg,0.0 g,3.60 g,0.00 mg,0.00 mg,1.90 g

In [27]:
# from nutr_mini extract total_fat and cholesterol for all rows
nutr_mini.loc[:,["total_fat","cholesterol"]]  # df.loc[rows,columns]

                                                   total_fat cholesterol
name
Desserts, prepared-from-recipe, apple crisp             3.4g           0
Frankfurter, low fat, meat and poultry                  2.8g        44mg
Whey, dried, acid                                       0.5g         3mg
Soybean, curd cheese                                    8.1g           0
Squash, without salt, boiled, cooked, frozen, b...      0.1g           0
Peas, raw, sprouted, mature seeds                       0.7g           0
Beverages, prepared with distilled water, brewe...        0g           0
KASHI, Oatmeal Dark Chocolate Cookies, TLC               16g           0
SPAGHETTIOS, SpaghettiOs with Meatballs                 2.8g         8mg
Snacks, unsalted, plain, potato chips                    35g           0

In [28]:
# Extract all columns for vitamin_b12 to end, for the first,second,third rows
nutr_mini.iloc[0:3,20:]

,vitamin_b12,vitamin_b6,vitamin_c,vitamin_d,vitamin_e,tocopherol_alpha,vitamin_k,calcium,copper,irom,...,fat,saturated_fatty_acids,monounsaturated_fatty_acids,polyunsaturated_fatty_acids,fatty_acids_total_trans,alcohol,ash,caffeine,theobromine,water
name,,,,,,,,,,,,,,,,,,,,,
"Desserts, prepared-from-recipe, apple crisp",0.00 mcg,0.040 mg,2.2 mg,0,0.38 mg,0.38 mg,4.1 mcg,35.00 mg,0.071 mg,0.82 mg,...,3.43 g,0.685 g,1.334 g,1.144 g,0.00 mg,0.0 g,1.07 g,0.00 mg,0.00 mg,62.91 g
"Frankfurter, low fat, meat and poultry",0.54 mcg,0.270 mg,0.4 mg,4.00 IU,0.20 mg,0.20 mg,0.3 mcg,12.00 mg,0.063 mg,0.91 mg,...,2.80 g,0.970 g,1.190 g,0.360 g,44.00 mg,0.0 g,3.40 g,0.00 mg,0.00 mg,69.90 g
"Whey, dried, acid",2.50 mcg,0.620 mg,0.9 mg,0.00 IU,0.00 mg,0.00 mg,0.0 mcg,2054.00 mg,0.050 mg,1.24 mg,...,0.54 g,0.342 g,0.149 g,0.021 g,3.00 mg,0.0 g,10.77 g,0.00 mg,0.00 mg,3.51 g

#### Rename method

In [29]:
name = [0,1,2,3]
age = [12.0,15.4,16.0,26.8]
height = [1.45,1.78,1.65,2.0]
df = pd.DataFrame({'Name':name,'Age':age,'Height':height},index=name)

In [30]:
df

   Name   Age  Height
0     0  12.0    1.45
1     1  15.4    1.78
2     2  16.0    1.65
3     3  26.8    2.00

In [31]:
df.rename(index={0:'Pikachu',1:'Bulbasaur',2:'Squirtle',3:'Charmender'},columns={'Age':'Age(kg)','Height':'Height(cm)'},inplace=True)

In [32]:
df

            Name  Age(kg)  Height(cm)
Pikachu        0     12.0        1.45
Bulbasaur      1     15.4        1.78
Squirtle       2     16.0        1.65
Charmender     3     26.8        2.00

In [33]:
df.axes[0]

Index(['Pikachu', 'Bulbasaur', 'Squirtle', 'Charmender'], dtype='object')

In [34]:
df.axes[1]

Index(['Name', 'Age(kg)', 'Height(cm)'], dtype='object')

In [35]:
df.axes  # return type is --> rows,columns

[Index(['Pikachu', 'Bulbasaur', 'Squirtle', 'Charmender'], dtype='object'),
 Index(['Name', 'Age(kg)', 'Height(cm)'], dtype='object')]

In [36]:
df

            Name  Age(kg)  Height(cm)
Pikachu        0     12.0        1.45
Bulbasaur      1     15.4        1.78
Squirtle       2     16.0        1.65
Charmender     3     26.8        2.00

In [44]:
df['Blastoise'] = 10,12,15,89

In [45]:
df

,Name,Age(kg),Height(cm),Jigglypuff,"(Blastoise, Jigglypuff)",Blastoise
Pikachu,0,12.0,1.45,10,10,10
Bulbasaur,1,15.4,1.78,12,12,12
Squirtle,2,16.0,1.65,15,15,15
Charmender,3,26.8,2.00,89,89,89

In [46]:
df

,Name,Age(kg),Height(cm),Jigglypuff,"(Blastoise, Jigglypuff)",Blastoise
Pikachu,0,12.0,1.45,10,10,10
Bulbasaur,1,15.4,1.78,12,12,12
Squirtle,2,16.0,1.65,15,15,15
Charmender,3,26.8,2.00,89,89,89

In [54]:
import numpy as np
df.loc['Pikachu','Height(cm)'] = np.nan

In [63]:
df

,Name,Age(kg),Height(cm),Jigglypuff,"(Blastoise, Jigglypuff)",Blastoise
Pikachu,0,12.0,NaN,10,10,10
Bulbasaur,1,15.4,1.78,12,12,12
Squirtle,2,16.0,1.65,15,15,15
Charmender,3,26.8,2.00,89,89,89

#### df.dropna()

In [64]:
df.dropna()

,Name,Age(kg),Height(cm),Jigglypuff,"(Blastoise, Jigglypuff)",Blastoise
Bulbasaur,1,15.4,1.78,12,12,12
Squirtle,2,16.0,1.65,15,15,15
Charmender,3,26.8,2.00,89,89,89

In [66]:
df.dropna(how='all',axis=1)

,Name,Age(kg),Height(cm),Jigglypuff,"(Blastoise, Jigglypuff)",Blastoise
Pikachu,0,12.0,NaN,10,10,10
Bulbasaur,1,15.4,1.78,12,12,12
Squirtle,2,16.0,1.65,15,15,15
Charmender,3,26.8,2.00,89,89,89

In [71]:
df

,Name,Age(kg),Height(cm),Jigglypuff,"(Blastoise, Jigglypuff)",Blastoise
Pikachu,0,12.0,NaN,10,10,10
Bulbasaur,1,15.4,1.78,12,12,12
Squirtle,2,16.0,1.65,15,15,15
Charmender,3,26.8,2.00,89,89,89

In [68]:
df.dropna(how='any',axis=1)

            Name  Age(kg)  Jigglypuff  (Blastoise, Jigglypuff)  Blastoise
Pikachu        0     12.0          10                       10         10
Bulbasaur      1     15.4          12                       12         12
Squirtle       2     16.0          15                       15         15
Charmender     3     26.8          89                       89         89

In [72]:
df.dropna(how='any',axis=0)

,Name,Age(kg),Height(cm),Jigglypuff,"(Blastoise, Jigglypuff)",Blastoise
Bulbasaur,1,15.4,1.78,12,12,12
Squirtle,2,16.0,1.65,15,15,15
Charmender,3,26.8,2.00,89,89,89

In [75]:
nutrition.head()

,serving_size,calories,total_fat,saturated_fat,cholesterol,sodium,choline,folate,folic_acid,niacin,...,fat,saturated_fatty_acids,monounsaturated_fatty_acids,polyunsaturated_fatty_acids,fatty_acids_total_trans,alcohol,ash,caffeine,theobromine,water
name,,,,,,,,,,,,,,,,,,,,,
Cornstarch,100 g,381,0.1g,NaN,0,9.00 mg,0.4 mg,0.00 mcg,0.00 mcg,0.000 mg,...,0.05 g,0.009 g,0.016 g,0.025 g,0.00 mg,0.0 g,0.09 g,0.00 mg,0.00 mg,8.32 g
"Nuts, pecans",100 g,691,72g,6.2g,0,0.00 mg,40.5 mg,22.00 mcg,0.00 mcg,1.167 mg,...,71.97 g,6.180 g,40.801 g,21.614 g,0.00 mg,0.0 g,1.49 g,0.00 mg,0.00 mg,3.52 g
"Eggplant, raw",100 g,25,0.2g,NaN,0,2.00 mg,6.9 mg,22.00 mcg,0.00 mcg,0.649 mg,...,0.18 g,0.034 g,0.016 g,0.076 g,0.00 mg,0.0 g,0.66 g,0.00 mg,0.00 mg,92.30 g
"Teff, uncooked",100 g,367,2.4g,0.4g,0,12.00 mg,13.1 mg,0,0,3.363 mg,...,2.38 g,0.449 g,0.589 g,1.071 g,0,0,2.37 g,0,0,8.82 g
"Sherbet, orange",100 g,144,2g,1.2g,1mg,46.00 mg,7.7 mg,4.00 mcg,0.00 mcg,0.063 mg,...,2.00 g,1.160 g,0.530 g,0.080 g,1.00 mg,0.0 g,0.40 g,0.00 mg,0.00 mg,66.10 g

In [79]:
nutrition.calories.head()

name
Cornstarch         381
Nuts, pecans       691
Eggplant, raw       25
Teff, uncooked     367
Sherbet, orange    144
Name: calories, dtype: int64

In [84]:
nutrition.calories.between(20,40)

name
Cornstarch                                                                                            False
Nuts, pecans                                                                                          False
Eggplant, raw                                                                                          True
Teff, uncooked                                                                                        False
Sherbet, orange                                                                                       False
                                                                                                      ...
Beef, raw, all grades, trimmed to 0" fat, separable lean and fat, boneless, top round roast, round    False
Lamb, cooked, separable lean only, composite of trimmed retail cuts, frozen, imported, New Zealand    False
Lamb, raw, separable lean and fat, composite of trimmed retail cuts, frozen, imported, New Zealand    False
Beef, raw, all grades, trimmed to 0" fat, separable lean only, boneless, eye of round roast, round    False
Beef, raw, all grades, trimmed to 0" fat, separable lean only, boneless, eye of round steak, round    False
Name: calories, Length: 8789, dtype: bool

In [98]:
nutrition[nutrition.calories.between(10,12)].sample()  # from nutrition dataframe we are getting a sample row who is having calories between 10 & 12 both are inclusive here

,serving_size,calories,total_fat,saturated_fat,cholesterol,sodium,choline,folate,folic_acid,niacin,...,fat,saturated_fatty_acids,monounsaturated_fatty_acids,polyunsaturated_fatty_acids,fatty_acids_total_trans,alcohol,ash,caffeine,theobromine,water
name,,,,,,,,,,,,,,,,,,,,,
"New zealand spinach, with salt, drained, boiled, cooked",100 g,12,0.2g,NaN,0,343.00 mg,0,8.00 mcg,0.00 mcg,0.390 mg,...,0.17 g,0.027 g,0.005 g,0.071 g,0.00 mg,0.0 g,1.60 g,0.00 mg,0.00 mg,94.80 g

In [114]:
nutrition.sort_values(by='choline',ascending = True)  # sort_values can be applied on dataframe directly as well

,serving_size,calories,total_fat,saturated_fat,cholesterol,sodium,choline,folate,folic_acid,niacin,...,fat,saturated_fatty_acids,monounsaturated_fatty_acids,polyunsaturated_fatty_acids,fatty_acids_total_trans,alcohol,ash,caffeine,theobromine,water
name,,,,,,,,,,,,,,,,,,,,,
"Amaranth leaves, with salt, drained, boiled, cooked",100 g,21,0.2g,0.1g,0,257.00 mg,0,57.00 mcg,0.00 mcg,0.559 mg,...,0.18 g,0.050 g,0.041 g,0.080 g,0.00 mg,0,2.11 g,0,0,91.49 g
"Rice, uncooked, enriched, short-grain, white",100 g,358,0.5g,0.1g,0,1.00 mg,0,231.00 mcg,225.00 mcg,4.113 mg,...,0.52 g,0.140 g,0.161 g,0.138 g,0.00 mg,0,0.54 g,0,0,13.29 g
"Rice, uncooked, unenriched, glutinous, white",100 g,370,0.6g,0.1g,0,7.00 mg,0,7.00 mcg,0.00 mcg,2.145 mg,...,0.55 g,0.111 g,0.200 g,0.198 g,0.00 mg,0,0.49 g,0,0,10.46 g
"USDA Commodity, cooked, frozen, ground bulk/coarse ground, beef",100 g,259,16g,5.7g,89mg,95.00 mg,0,9.00 mcg,0.00 mcg,3.376 mg,...,16.34 g,5.744 g,7.504 g,0.620 g,89.00 mg,0.0 g,0.95 g,0.00 mg,0.00 mg,56.49 g
"CAMPBELL'S Red and White, condensed, Italian Style Wedding Soup",100 g,71,2g,0.8g,8mg,643.00 mg,0,0,0,0,...,1.98 g,0.794 g,0,0,8.00 mg,0,2.12 g,0,0,83.20 g
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
"POPEYES, skin and breading removed, meat only, Breast, Mild, Fried Chicken",100 g,157,4.5g,1.4g,97mg,526.00 mg,99.7 mg,0,0,9.393 mg,...,4.52 g,1.368 g,1.789 g,0.596 g,97.00 mg,0,2.26 g,0,0,64.77 g
"Pork, braised, cooked, separable lean only, bone-in, center rib (chops), loin, fresh",100 g,208,9.3g,2.4g,79mg,72.00 mg,99.8 mg,0.00 mcg,0.00 mcg,7.880 mg,...,9.32 g,2.389 g,5.368 g,1.009 g,79.00 mg,0.0 g,1.13 g,0.00 mg,0.00 mg,61.56 g
"Beef, braised, cooked, select, trimmed to 0"" fat, separable lean only, boneless, under blade pot roast, chuck",100 g,216,9.4g,3.5g,102mg,67.00 mg,99.8 mg,7.00 mcg,0.00 mcg,3.745 mg,...,9.44 g,3.487 g,4.164 g,0.520 g,102.00 mg,0.0 g,1.58 g,0.00 mg,0.00 mg,58.79 g
"Veal, raw, separable lean only, shank",100 g,94,1.6g,0.6g,62mg,109.00 mg,99.9 mg,3.00 mcg,0.00 mcg,5.370 mg,...,1.64 g,0.639 g,0.758 g,0.104 g,62.00 mg,0.0 g,0.98 g,0.00 mg,0.00 mg,77.96 g
"Pork, braised, cooked, separable lean and fat, spareribs, fresh",100 g,397,30g,11g,121mg,93.00 mg,99.9 mg,4.00 mcg,0.00 mcg,5.475 mg,...,30.30 g,11.120 g,13.480 g,2.730 g,121.00 mg,0.0 g,1.12 g,0.00 mg,0.00 mg,40.42 g

In [116]:
nutrition.niacin.sort_values()

name
WENDY'S, with cheese, Double Stack                                          0
CAMPBELL'S CHUNKY Soups, Grilled Chicken & Sausage Gumbo Soup               0
Sea lion, fat (Alaska Native), Steller                                      0
Veal, raw, separable lean only, bone-in, fore, shank, Australian            0
Beverages, DANNON Fluoride To Go, non-carbonated, bottled, water            0
                                                                      ...
Corn flour, enriched, masa, yellow                                   9.932 mg
Corn flour, white, enriched, masa                                    9.932 mg
Spices, dried, parsley                                               9.943 mg
Canadian bacon, pan-fried, cooked                                    9.988 mg
Cereals ready-to-eat, RALSTON Enriched Wheat Bran flakes            90.567 mg
Name: niacin, Length: 8789, dtype: object

In [120]:
nutrition.calories.nlargest(10)

name
Fish oil, cod liver                       902
Fish oil, menhaden                        902
Fat, mutton tallow                        902
Fish oil, sardine                         902
Fish oil, herring                         902
Fish oil, salmon                          902
Fat, beef tallow                          902
Lard                                      902
Fish oil, fully hydrogenated, menhaden    902
Fat, chicken                              900
Name: calories, dtype: int64

In [124]:
nutrition.calories.nsmallest(2)  # use this to get series output

name
Salt, table                      0
Leavening agents, baking soda    0
Name: calories, dtype: int64

In [123]:
nutrition.nsmallest(2,'calories')  # use this to get dataframe output

,serving_size,calories,total_fat,saturated_fat,cholesterol,sodium,choline,folate,folic_acid,niacin,...,fat,saturated_fatty_acids,monounsaturated_fatty_acids,polyunsaturated_fatty_acids,fatty_acids_total_trans,alcohol,ash,caffeine,theobromine,water
name,,,,,,,,,,,,,,,,,,,,,
"Salt, table",100 g,0,0g,NaN,0,38758.00 mg,0.0 mg,0.00 mcg,0.00 mcg,0.000 mg,...,0.00 g,0.000 g,0.000 g,0.000 g,0.00 mg,0.0 g,99.80 g,0.00 mg,0.00 mg,0.20 g
"Leavening agents, baking soda",100 g,0,0g,NaN,0,27360.00 mg,0.0 mg,0.00 mcg,0.00 mcg,0.000 mg,...,0.00 g,0.000 g,0.000 g,0.000 g,0.00 mg,0.0 g,36.90 g,0.00 mg,0.00 mg,0.20 g

In [125]:
nutrition.axes

[Index(['Cornstarch', 'Nuts, pecans', 'Eggplant, raw', 'Teff, uncooked',
        'Sherbet, orange', 'Cauliflower, raw', 'Taro leaves, raw',
        'Lamb, raw, ground', 'Cheese, camembert', 'Vegetarian fillets',
        ...
        'Beef, braised, cooked, all grades, trimmed to 1/8" fat, separable lean and fat, flat half, brisket',
        'Beef, raw, select, trimmed to 1/8" fat, separable lean only, lip-on, boneless, rib eye steak/roast',
        'Beef, raw, choice, trimmed to 1/8" fat, separable lean only, lip-on, boneless, rib eye steak/roast',
        'Oil, uses similar to 95 degree hard butter, confection fat, palm kernel (hydrogenated), industrial',
        'Beef, raw, all grades, trimmed to 0" fat, separable lean and fat, boneless, top round steak, round',
        'Beef, raw, all grades, trimmed to 0" fat, separable lean and fat, boneless, top round roast, round',
        'Lamb, cooked, separable lean only, composite of trimmed retail cuts, frozen, imported, New Zealand',
        'Lamb, raw, separable lean and fat, composite of trimmed retail cuts, frozen, imported, New Zealand',
        'Beef, raw, all grades, trimmed to 0" fat, separable lean only, boneless, eye of round roast, round',
        'Beef, raw, all grades, trimmed to 0" fat, separable lean only, boneless, eye of round steak, round'],
       dtype='object', name='name', length=8789),
 Index(['serving_size', 'calories', 'total_fat', 'saturated_fat', 'cholesterol',
        'sodium', 'choline', 'folate', 'folic_acid', 'niacin',
        'pantothenic_acid', 'riboflavin', 'thiamin', 'vitamin_a',
        'vitamin_a_rae', 'carotene_alpha', 'carotene_beta',
        'cryptoxanthin_beta', 'lutein_zeaxanthin', 'lucopene', 'vitamin_b12',
        'vitamin_b6', 'vitamin_c', 'vitamin_d', 'vitamin_e', 'tocopherol_alpha',
        'vitamin_k', 'calcium', 'copper', 'irom', 'magnesium', 'manganese',
        'phosphorous', 'potassium', 'selenium', 'zink', 'protein', 'alanine',
        'arginine', 'aspartic_acid', 'cystine', 'glutamic_acid', 'glycine',
        'histidine', 'hydroxyproline', 'isoleucine', 'leucine', 'lysine',
        'methionine', 'phenylalanine', 'proline', 'serine', 'threonine',
        'tryptophan', 'tyrosine', 'valine', 'carbohydrate', 'fiber', 'sugars',
        'fructose', 'galactose', 'glucose', 'lactose', 'maltose', 'sucrose',
        'fat', 'saturated_fatty_acids', 'monounsaturated_fatty_acids',
        'polyunsaturated_fatty_acids', 'fatty_acids_total_trans', 'alcohol',
        'ash', 'caffeine', 'theobromine', 'water'],
       dtype='object')]

In [137]:
nutrition.nsmallest(2,['calories'])

,serving_size,calories,total_fat,saturated_fat,cholesterol,sodium,choline,folate,folic_acid,niacin,...,fat,saturated_fatty_acids,monounsaturated_fatty_acids,polyunsaturated_fatty_acids,fatty_acids_total_trans,alcohol,ash,caffeine,theobromine,water
name,,,,,,,,,,,,,,,,,,,,,
"Salt, table",100 g,0,0g,NaN,0,38758.00 mg,0.0 mg,0.00 mcg,0.00 mcg,0.000 mg,...,0.00 g,0.000 g,0.000 g,0.000 g,0.00 mg,0.0 g,99.80 g,0.00 mg,0.00 mg,0.20 g
"Leavening agents, baking soda",100 g,0,0g,NaN,0,27360.00 mg,0.0 mg,0.00 mcg,0.00 mcg,0.000 mg,...,0.00 g,0.000 g,0.000 g,0.000 g,0.00 mg,0.0 g,36.90 g,0.00 mg,0.00 mg,0.20 g

In [139]:
nutrition.thiamin

name
Cornstarch                                                                                            0.000 mg
Nuts, pecans                                                                                          0.660 mg
Eggplant, raw                                                                                         0.039 mg
Teff, uncooked                                                                                        0.390 mg
Sherbet, orange                                                                                       0.027 mg
                                                                                                        ...
Beef, raw, all grades, trimmed to 0" fat, separable lean and fat, boneless, top round roast, round    0.063 mg
Lamb, cooked, separable lean only, composite of trimmed retail cuts, frozen, imported, New Zealand    0.130 mg
Lamb, raw, separable lean and fat, composite of trimmed retail cuts, frozen, imported, New Zealand    0.130 mg
Beef, raw, all grades, trimmed to 0" fat, separable lean only, boneless, eye of round roast, round    0.063 mg
Beef, raw, all grades, trimmed to 0" fat, separable lean only, boneless, eye of round steak, round    0.063 mg
Name: thiamin, Length: 8789, dtype: object

##### Skill Challenge

In [142]:
# find 10 foods having most vitamin_b12. What do they have in comman?
nutrition.vitamin_b12.nlargest()

TypeError: Cannot use method 'nlargest' with dtype object