#### What is dataframe

In [1]:
import pandas as pd

In [2]:
names = ["Tony","Bruce","Steve","Chris"]
age = [45,46,100,55]

In [3]:
df = pd.DataFrame({"Names":names,"Age":age})

In [4]:
df

   Names  Age
0   Tony   45
1  Bruce   46
2  Steve  100
3  Chris   55

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Names   4 non-null      object
 1   Age     4 non-null      int64
dtypes: int64(1), object(1)
memory usage: 196.0+ bytes

In [6]:
dataurl = 'https://andybek.com/pandas-nutrition'

In [7]:
nutrition = pd.read_csv(dataurl)

In [8]:
nutrition.sample(3)
# nutrition.head()

,Unnamed: 0,name,serving_size,calories,total_fat,saturated_fat,cholesterol,sodium,choline,folate,...,fat,saturated_fatty_acids,monounsaturated_fatty_acids,polyunsaturated_fatty_acids,fatty_acids_total_trans,alcohol,ash,caffeine,theobromine,water
389,389,"Egg, dried, white",100 g,382,0g,NaN,0,1280.00 mg,8.4 mg,18.00 mcg,...,0.00 g,0.000 g,0.000 g,0.000 g,0.00 mg,0.0 g,5.30 g,0.00 mg,0.00 mg,5.80 g
6845,6845,"Lima beans, without salt, drained, boiled, coo...",100 g,103,0.3g,0.1g,0,69.00 mg,36.3 mg,21.00 mcg,...,0.34 g,0.077 g,0.020 g,0.163 g,0.00 mg,0.0 g,1.30 g,0.00 mg,0.00 mg,72.98 g
824,824,"Cream, heavy whipping, fluid",100 g,340,36g,23g,113mg,27.00 mg,16.8 mg,4.00 mcg,...,36.08 g,23.032 g,9.101 g,1.570 g,113.00 mg,0.0 g,0.53 g,0.00 mg,0.00 mg,57.81 g

In [9]:
nutrition.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8789 entries, 0 to 8788
Data columns (total 77 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Unnamed: 0                   8789 non-null   int64
 1   name                         8789 non-null   object
 2   serving_size                 8789 non-null   object
 3   calories                     8789 non-null   int64
 4   total_fat                    8789 non-null   object
 5   saturated_fat                7199 non-null   object
 6   cholesterol                  8789 non-null   object
 7   sodium                       8789 non-null   object
 8   choline                      8789 non-null   object
 9   folate                       8789 non-null   object
 10  folic_acid                   8789 non-null   object
 11  niacin                       8789 non-null   object
 12  pantothenic_acid             8789 non-null   object
 13  riboflavin                   8789 non-null   object
 14  thiamin                      8789 non-null   object
 15  vitamin_a                    8789 non-null   object
 16  vitamin_a_rae                8789 non-null   object
 17  carotene_alpha               8789 non-null   object
 18  carotene_beta                8789 non-null   object
 19  cryptoxanthin_beta           8789 non-null   object
 20  lutein_zeaxanthin            8789 non-null   object
 21  lucopene                     8789 non-null   int64
 22  vitamin_b12                  8789 non-null   object
 23  vitamin_b6                   8789 non-null   object
 24  vitamin_c                    8789 non-null   object
 25  vitamin_d                    8789 non-null   object
 26  vitamin_e                    8789 non-null   object
 27  tocopherol_alpha             8789 non-null   object
 28  vitamin_k                    8789 non-null   object
 29  calcium                      8789 non-null   object
 30  copper                       8789 non-null   object
 31  irom                         8789 non-null   object
 32  magnesium                    8789 non-null   object
 33  manganese                    8789 non-null   object
 34  phosphorous                  8789 non-null   object
 35  potassium                    8789 non-null   object
 36  selenium                     8789 non-null   object
 37  zink                         8789 non-null   object
 38  protein                      8789 non-null   object
 39  alanine                      8789 non-null   object
 40  arginine                     8789 non-null   object
 41  aspartic_acid                8789 non-null   object
 42  cystine                      8789 non-null   object
 43  glutamic_acid                8789 non-null   object
 44  glycine                      8789 non-null   object
 45  histidine                    8789 non-null   object
 46  hydroxyproline               8789 non-null   object
 47  isoleucine                   8789 non-null   object
 48  leucine                      8789 non-null   object
 49  lysine                       8789 non-null   object
 50  methionine                   8789 non-null   object
 51  phenylalanine                8789 non-null   object
 52  proline                      8789 non-null   object
 53  serine                       8789 non-null   object
 54  threonine                    8789 non-null   object
 55  tryptophan                   8789 non-null   object
 56  tyrosine                     8789 non-null   object
 57  valine                       8789 non-null   object
 58  carbohydrate                 8789 non-null   object
 59  fiber                        8789 non-null   object
 60  sugars                       8789 non-null   object
 61  fructose                     8789 non-null   object
 62  galactose                    8789 non-null   object
 63  glucose                      8789 non-null   object
 64  lactose                      8789 non-null   object
 65  maltose                      8789 non-null   object
 66  sucrose                      8789 non-null   object
 67  fat                          8789 non-null   object
 68  saturated_fatty_acids        8789 non-null   object
 69  monounsaturated_fatty_acids  8789 non-null   object
 70  polyunsaturated_fatty_acids  8789 non-null   object
 71  fatty_acids_total_trans      8789 non-null   object
 72  alcohol                      8789 non-null   object
 73  ash                          8789 non-null   object
 74  caffeine                     8789 non-null   object
 75  theobromine                  8789 non-null   object
 76  water                        8789 non-null   object
dtypes: int64(3), object(74)
memory usage: 5.2+ MB

In [10]:
# dropping Unnamed:0 column as its extra
nutrition.drop('Unnamed: 0',axis=1)  # axis 1 stands for columns and axis 0 stands for rows

,name,serving_size,calories,total_fat,saturated_fat,cholesterol,sodium,choline,folate,folic_acid,...,fat,saturated_fatty_acids,monounsaturated_fatty_acids,polyunsaturated_fatty_acids,fatty_acids_total_trans,alcohol,ash,caffeine,theobromine,water
0,Cornstarch,100 g,381,0.1g,NaN,0,9.00 mg,0.4 mg,0.00 mcg,0.00 mcg,...,0.05 g,0.009 g,0.016 g,0.025 g,0.00 mg,0.0 g,0.09 g,0.00 mg,0.00 mg,8.32 g
1,"Nuts, pecans",100 g,691,72g,6.2g,0,0.00 mg,40.5 mg,22.00 mcg,0.00 mcg,...,71.97 g,6.180 g,40.801 g,21.614 g,0.00 mg,0.0 g,1.49 g,0.00 mg,0.00 mg,3.52 g
2,"Eggplant, raw",100 g,25,0.2g,NaN,0,2.00 mg,6.9 mg,22.00 mcg,0.00 mcg,...,0.18 g,0.034 g,0.016 g,0.076 g,0.00 mg,0.0 g,0.66 g,0.00 mg,0.00 mg,92.30 g
3,"Teff, uncooked",100 g,367,2.4g,0.4g,0,12.00 mg,13.1 mg,0,0,...,2.38 g,0.449 g,0.589 g,1.071 g,0,0,2.37 g,0,0,8.82 g
4,"Sherbet, orange",100 g,144,2g,1.2g,1mg,46.00 mg,7.7 mg,4.00 mcg,0.00 mcg,...,2.00 g,1.160 g,0.530 g,0.080 g,1.00 mg,0.0 g,0.40 g,0.00 mg,0.00 mg,66.10 g
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8784,"Beef, raw, all grades, trimmed to 0"" fat, sepa...",100 g,125,3.5g,1.4g,62mg,54.00 mg,64.5 mg,4.00 mcg,0.00 mcg,...,3.50 g,1.353 g,1.554 g,0.244 g,62.00 mg,0.0 g,1.11 g,0.00 mg,0.00 mg,72.51 g
8785,"Lamb, cooked, separable lean only, composite o...",100 g,206,8.9g,3.9g,109mg,50.00 mg,0,0.00 mcg,0.00 mcg,...,8.86 g,3.860 g,3.480 g,0.520 g,109.00 mg,0,1.60 g,0,0,59.95 g
8786,"Lamb, raw, separable lean and fat, composite o...",100 g,277,23g,12g,78mg,39.00 mg,0,1.00 mcg,0.00 mcg,...,22.74 g,11.570 g,8.720 g,0.980 g,78.00 mg,0,0.92 g,0,0,59.80 g
8787,"Beef, raw, all grades, trimmed to 0"" fat, sepa...",100 g,121,3g,1.1g,60mg,53.00 mg,64.2 mg,4.00 mcg,0.00 mcg,...,3.04 g,1.086 g,1.266 g,0.233 g,60.00 mg,0.0 g,1.10 g,0.00 mg,0.00 mg,73.43 g
8788,"Beef, raw, all grades, trimmed to 0"" fat, sepa...",100 g,121,3g,1.1g,60mg,53.00 mg,64.2 mg,4.00 mcg,0.00 mcg,...,3.04 g,1.086 g,1.266 g,0.233 g,60.00 mg,0.0 g,1.10 g,0.00 mg,0.00 mg,73.43 g

In [11]:
nutrition.head()

,Unnamed: 0,name,serving_size,calories,total_fat,saturated_fat,cholesterol,sodium,choline,folate,...,fat,saturated_fatty_acids,monounsaturated_fatty_acids,polyunsaturated_fatty_acids,fatty_acids_total_trans,alcohol,ash,caffeine,theobromine,water
0,0,Cornstarch,100 g,381,0.1g,NaN,0,9.00 mg,0.4 mg,0.00 mcg,...,0.05 g,0.009 g,0.016 g,0.025 g,0.00 mg,0.0 g,0.09 g,0.00 mg,0.00 mg,8.32 g
1,1,"Nuts, pecans",100 g,691,72g,6.2g,0,0.00 mg,40.5 mg,22.00 mcg,...,71.97 g,6.180 g,40.801 g,21.614 g,0.00 mg,0.0 g,1.49 g,0.00 mg,0.00 mg,3.52 g
2,2,"Eggplant, raw",100 g,25,0.2g,NaN,0,2.00 mg,6.9 mg,22.00 mcg,...,0.18 g,0.034 g,0.016 g,0.076 g,0.00 mg,0.0 g,0.66 g,0.00 mg,0.00 mg,92.30 g
3,3,"Teff, uncooked",100 g,367,2.4g,0.4g,0,12.00 mg,13.1 mg,0,...,2.38 g,0.449 g,0.589 g,1.071 g,0,0,2.37 g,0,0,8.82 g
4,4,"Sherbet, orange",100 g,144,2g,1.2g,1mg,46.00 mg,7.7 mg,4.00 mcg,...,2.00 g,1.160 g,0.530 g,0.080 g,1.00 mg,0.0 g,0.40 g,0.00 mg,0.00 mg,66.10 g

In [12]:
nutrition = pd.read_csv(dataurl, index_col=[0])  # here 0 is telling use column 0 as index while fetching data from dataurl

In [13]:
nutrition

,name,serving_size,calories,total_fat,saturated_fat,cholesterol,sodium,choline,folate,folic_acid,...,fat,saturated_fatty_acids,monounsaturated_fatty_acids,polyunsaturated_fatty_acids,fatty_acids_total_trans,alcohol,ash,caffeine,theobromine,water
0,Cornstarch,100 g,381,0.1g,NaN,0,9.00 mg,0.4 mg,0.00 mcg,0.00 mcg,...,0.05 g,0.009 g,0.016 g,0.025 g,0.00 mg,0.0 g,0.09 g,0.00 mg,0.00 mg,8.32 g
1,"Nuts, pecans",100 g,691,72g,6.2g,0,0.00 mg,40.5 mg,22.00 mcg,0.00 mcg,...,71.97 g,6.180 g,40.801 g,21.614 g,0.00 mg,0.0 g,1.49 g,0.00 mg,0.00 mg,3.52 g
2,"Eggplant, raw",100 g,25,0.2g,NaN,0,2.00 mg,6.9 mg,22.00 mcg,0.00 mcg,...,0.18 g,0.034 g,0.016 g,0.076 g,0.00 mg,0.0 g,0.66 g,0.00 mg,0.00 mg,92.30 g
3,"Teff, uncooked",100 g,367,2.4g,0.4g,0,12.00 mg,13.1 mg,0,0,...,2.38 g,0.449 g,0.589 g,1.071 g,0,0,2.37 g,0,0,8.82 g
4,"Sherbet, orange",100 g,144,2g,1.2g,1mg,46.00 mg,7.7 mg,4.00 mcg,0.00 mcg,...,2.00 g,1.160 g,0.530 g,0.080 g,1.00 mg,0.0 g,0.40 g,0.00 mg,0.00 mg,66.10 g
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8784,"Beef, raw, all grades, trimmed to 0"" fat, sepa...",100 g,125,3.5g,1.4g,62mg,54.00 mg,64.5 mg,4.00 mcg,0.00 mcg,...,3.50 g,1.353 g,1.554 g,0.244 g,62.00 mg,0.0 g,1.11 g,0.00 mg,0.00 mg,72.51 g
8785,"Lamb, cooked, separable lean only, composite o...",100 g,206,8.9g,3.9g,109mg,50.00 mg,0,0.00 mcg,0.00 mcg,...,8.86 g,3.860 g,3.480 g,0.520 g,109.00 mg,0,1.60 g,0,0,59.95 g
8786,"Lamb, raw, separable lean and fat, composite o...",100 g,277,23g,12g,78mg,39.00 mg,0,1.00 mcg,0.00 mcg,...,22.74 g,11.570 g,8.720 g,0.980 g,78.00 mg,0,0.92 g,0,0,59.80 g
8787,"Beef, raw, all grades, trimmed to 0"" fat, sepa...",100 g,121,3g,1.1g,60mg,53.00 mg,64.2 mg,4.00 mcg,0.00 mcg,...,3.04 g,1.086 g,1.266 g,0.233 g,60.00 mg,0.0 g,1.10 g,0.00 mg,0.00 mg,73.43 g
8788,"Beef, raw, all grades, trimmed to 0"" fat, sepa...",100 g,121,3g,1.1g,60mg,53.00 mg,64.2 mg,4.00 mcg,0.00 mcg,...,3.04 g,1.086 g,1.266 g,0.233 g,60.00 mg,0.0 g,1.10 g,0.00 mg,0.00 mg,73.43 g

In [14]:
nutrition.index

Index([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,
       ...
       8779, 8780, 8781, 8782, 8783, 8784, 8785, 8786, 8787, 8788],
      dtype='int64', length=8789)

In [15]:
nutrition = nutrition.set_index('name')

In [16]:
nutrition.head(8)

,serving_size,calories,total_fat,saturated_fat,cholesterol,sodium,choline,folate,folic_acid,niacin,...,fat,saturated_fatty_acids,monounsaturated_fatty_acids,polyunsaturated_fatty_acids,fatty_acids_total_trans,alcohol,ash,caffeine,theobromine,water
name,,,,,,,,,,,,,,,,,,,,,
Cornstarch,100 g,381,0.1g,NaN,0,9.00 mg,0.4 mg,0.00 mcg,0.00 mcg,0.000 mg,...,0.05 g,0.009 g,0.016 g,0.025 g,0.00 mg,0.0 g,0.09 g,0.00 mg,0.00 mg,8.32 g
"Nuts, pecans",100 g,691,72g,6.2g,0,0.00 mg,40.5 mg,22.00 mcg,0.00 mcg,1.167 mg,...,71.97 g,6.180 g,40.801 g,21.614 g,0.00 mg,0.0 g,1.49 g,0.00 mg,0.00 mg,3.52 g
"Eggplant, raw",100 g,25,0.2g,NaN,0,2.00 mg,6.9 mg,22.00 mcg,0.00 mcg,0.649 mg,...,0.18 g,0.034 g,0.016 g,0.076 g,0.00 mg,0.0 g,0.66 g,0.00 mg,0.00 mg,92.30 g
"Teff, uncooked",100 g,367,2.4g,0.4g,0,12.00 mg,13.1 mg,0,0,3.363 mg,...,2.38 g,0.449 g,0.589 g,1.071 g,0,0,2.37 g,0,0,8.82 g
"Sherbet, orange",100 g,144,2g,1.2g,1mg,46.00 mg,7.7 mg,4.00 mcg,0.00 mcg,0.063 mg,...,2.00 g,1.160 g,0.530 g,0.080 g,1.00 mg,0.0 g,0.40 g,0.00 mg,0.00 mg,66.10 g
"Cauliflower, raw",100 g,25,0.3g,0.1g,0,30.00 mg,44.3 mg,57.00 mcg,0.00 mcg,0.507 mg,...,0.28 g,0.130 g,0.034 g,0.031 g,0.00 mg,0.0 g,0.76 g,0.00 mg,0.00 mg,92.07 g
"Taro leaves, raw",100 g,42,0.7g,0.2g,0,3.00 mg,12.8 mg,126.00 mcg,0.00 mcg,1.513 mg,...,0.74 g,0.151 g,0.060 g,0.307 g,0.00 mg,0.0 g,1.92 g,0.00 mg,0.00 mg,85.66 g
"Lamb, raw, ground",100 g,282,23g,10g,73mg,59.00 mg,69.3 mg,18.00 mcg,0.00 mcg,5.960 mg,...,23.41 g,10.190 g,9.600 g,1.850 g,73.00 mg,0.0 g,0.87 g,0.00 mg,0.00 mg,59.47 g

In [17]:
nutrition.loc["Eggplant, raw"]

serving_size       100 g
calories              25
total_fat           0.2g
saturated_fat        NaN
cholesterol            0
                  ...
alcohol            0.0 g
ash               0.66 g
caffeine         0.00 mg
theobromine      0.00 mg
water            92.30 g
Name: Eggplant, raw, Length: 75, dtype: object

In [18]:
nutrition.loc["Cornstarch","calories"]  # df.loc[row,column]

np.int64(381)

In [19]:
nutrition.loc["Sherbet, orange":"Lamb, raw, ground","calories":"sodium"]  # df.loc[[row:row],[column:column]]

                   calories total_fat saturated_fat cholesterol    sodium
name
Sherbet, orange         144        2g          1.2g         1mg  46.00 mg
Cauliflower, raw         25      0.3g          0.1g           0  30.00 mg
Taro leaves, raw         42      0.7g          0.2g           0   3.00 mg
Lamb, raw, ground       282       23g           10g        73mg  59.00 mg

In [20]:
nutrition.iloc[5,7]  # df.iloc[row,column]

'57.00 mcg'

In [21]:
nutrition.iloc[[12,17,25],6:9]  # this is dataframe slicing iloc[[rows],columns slicing]

                       choline     folate folic_acid
name
Mango nectar, canned    1.5 mg   7.00 mcg   0.00 mcg
Peppers, raw, jalapeno  7.5 mg  27.00 mcg   0.00 mcg
PACE, Green Taco Sauce       0          0          0

In [22]:
nutrition.iloc[[10,20,30],[10,30,40]]  # this is dataframe slicing iloc[[rows],[columns]]

                       pantothenic_acid magnesium  cystine
name
PACE, Picante Sauce                   0         0        0
Grapes, raw, muscadine                0  14.00 mg        0
Pasta, unenriched, dry         0.431 mg  53.00 mg  0.255 g

In [23]:
nutrition.head(2)

,serving_size,calories,total_fat,saturated_fat,cholesterol,sodium,choline,folate,folic_acid,niacin,...,fat,saturated_fatty_acids,monounsaturated_fatty_acids,polyunsaturated_fatty_acids,fatty_acids_total_trans,alcohol,ash,caffeine,theobromine,water
name,,,,,,,,,,,,,,,,,,,,,
Cornstarch,100 g,381,0.1g,NaN,0,9.00 mg,0.4 mg,0.00 mcg,0.00 mcg,0.000 mg,...,0.05 g,0.009 g,0.016 g,0.025 g,0.00 mg,0.0 g,0.09 g,0.00 mg,0.00 mg,8.32 g
"Nuts, pecans",100 g,691,72g,6.2g,0,0.00 mg,40.5 mg,22.00 mcg,0.00 mcg,1.167 mg,...,71.97 g,6.180 g,40.801 g,21.614 g,0.00 mg,0.0 g,1.49 g,0.00 mg,0.00 mg,3.52 g

In [24]:
nutrition.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8789 entries, Cornstarch to Beef, raw, all grades, trimmed to 0" fat, separable lean only, boneless, eye of round steak, round
Data columns (total 75 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   serving_size                 8789 non-null   object
 1   calories                     8789 non-null   int64
 2   total_fat                    8789 non-null   object
 3   saturated_fat                7199 non-null   object
 4   cholesterol                  8789 non-null   object
 5   sodium                       8789 non-null   object
 6   choline                      8789 non-null   object
 7   folate                       8789 non-null   object
 8   folic_acid                   8789 non-null   object
 9   niacin                       8789 non-null   object
 10  pantothenic_acid             8789 non-null   object
 11  riboflavin                   8789 non-null   object
 12  thiamin                      8789 non-null   object
 13  vitamin_a                    8789 non-null   object
 14  vitamin_a_rae                8789 non-null   object
 15  carotene_alpha               8789 non-null   object
 16  carotene_beta                8789 non-null   object
 17  cryptoxanthin_beta           8789 non-null   object
 18  lutein_zeaxanthin            8789 non-null   object
 19  lucopene                     8789 non-null   int64
 20  vitamin_b12                  8789 non-null   object
 21  vitamin_b6                   8789 non-null   object
 22  vitamin_c                    8789 non-null   object
 23  vitamin_d                    8789 non-null   object
 24  vitamin_e                    8789 non-null   object
 25  tocopherol_alpha             8789 non-null   object
 26  vitamin_k                    8789 non-null   object
 27  calcium                      8789 non-null   object
 28  copper                       8789 non-null   object
 29  irom                         8789 non-null   object
 30  magnesium                    8789 non-null   object
 31  manganese                    8789 non-null   object
 32  phosphorous                  8789 non-null   object
 33  potassium                    8789 non-null   object
 34  selenium                     8789 non-null   object
 35  zink                         8789 non-null   object
 36  protein                      8789 non-null   object
 37  alanine                      8789 non-null   object
 38  arginine                     8789 non-null   object
 39  aspartic_acid                8789 non-null   object
 40  cystine                      8789 non-null   object
 41  glutamic_acid                8789 non-null   object
 42  glycine                      8789 non-null   object
 43  histidine                    8789 non-null   object
 44  hydroxyproline               8789 non-null   object
 45  isoleucine                   8789 non-null   object
 46  leucine                      8789 non-null   object
 47  lysine                       8789 non-null   object
 48  methionine                   8789 non-null   object
 49  phenylalanine                8789 non-null   object
 50  proline                      8789 non-null   object
 51  serine                       8789 non-null   object
 52  threonine                    8789 non-null   object
 53  tryptophan                   8789 non-null   object
 54  tyrosine                     8789 non-null   object
 55  valine                       8789 non-null   object
 56  carbohydrate                 8789 non-null   object
 57  fiber                        8789 non-null   object
 58  sugars                       8789 non-null   object
 59  fructose                     8789 non-null   object
 60  galactose                    8789 non-null   object
 61  glucose                      8789 non-null   object
 62  lactose                      8789 non-null   object
 63  maltose                      8789 non-null   object
 64  sucrose                      8789 non-null   object
 65  fat                          8789 non-null   object
 66  saturated_fatty_acids        8789 non-null   object
 67  monounsaturated_fatty_acids  8789 non-null   object
 68  polyunsaturated_fatty_acids  8789 non-null   object
 69  fatty_acids_total_trans      8789 non-null   object
 70  alcohol                      8789 non-null   object
 71  ash                          8789 non-null   object
 72  caffeine                     8789 non-null   object
 73  theobromine                  8789 non-null   object
 74  water                        8789 non-null   object
dtypes: int64(2), object(73)
memory usage: 5.3+ MB

### Skill Challenge

In [34]:
# Randomly select 10 food items and assign df to nutr_mini
nutr_mini = nutrition.sample(10)

In [36]:
nutr_mini

,serving_size,calories,total_fat,saturated_fat,cholesterol,sodium,choline,folate,folic_acid,niacin,...,fat,saturated_fatty_acids,monounsaturated_fatty_acids,polyunsaturated_fatty_acids,fatty_acids_total_trans,alcohol,ash,caffeine,theobromine,water
name,,,,,,,,,,,,,,,,,,,,,
"Oil, bowhead (Alaska Native), whale",100 g,900,100g,NaN,0,0,0,0,0,0.000 mg,...,100.00 g,0,0,0,0,0,0.00 g,0,0,0.00 g
"Soup, ready-to-serve, canned, chunky chicken noodle",100 g,41,1.2g,0.6g,5mg,306.00 mg,6.2 mg,9.00 mcg,3.00 mcg,1.196 mg,...,1.16 g,0.627 g,0.298 g,0.172 g,5.00 mg,0.0 g,1.40 g,0.00 mg,0.00 mg,89.88 g
"Muffins, oat bran",100 g,270,7.4g,1.1g,0,393.00 mg,6.6 mg,89.00 mcg,71.00 mcg,0.420 mg,...,7.40 g,1.087 g,1.695 g,4.129 g,0.00 mg,0.0 g,2.30 g,0.00 mg,0.00 mg,35.00 g
"Turkey, bone removed, with skin, cooked, smoked, wing",100 g,221,12g,3.4g,81mg,996.00 mg,68.7 mg,6.00 mcg,0.00 mcg,5.730 mg,...,12.41 g,3.383 g,4.651 g,2.934 g,81.00 mg,0.0 g,0.70 g,0.00 mg,0.00 mg,59.50 g
"SMART SOUP, Indian Bean Masala",100 g,57,0.9g,0.2g,0,92.00 mg,0,0,0,0,...,0.88 g,0.180 g,0,0,0.00 mg,0,1.10 g,0,0,84.30 g
"Soup, canned, HEALTHY CHOICE Chicken and Rice Soup",100 g,37,0.6g,0.2g,7mg,181.00 mg,0,0,0,0,...,0.55 g,0.170 g,0.230 g,0.130 g,7.00 mg,0,0.90 g,0,0,90.31 g
"CAMPBELL'S Red and White, condensed, Minestrone Soup",100 g,71,0.8g,0.4g,4mg,516.00 mg,0,0,0,0,...,0.79 g,0.397 g,0.000 g,0.000 g,4.00 mg,0,2.84 g,0,0,79.70 g
"Lamb, raw, separable lean only, boneless, loin, imported, New Zealand",100 g,120,3.8g,1.2g,66mg,60.00 mg,0,0,0,6.356 mg,...,3.77 g,1.187 g,0.923 g,0.272 g,66.00 mg,0.0 g,1.17 g,0.00 mg,0.00 mg,74.54 g
"Restaurant, orange chicken, Chinese",100 g,262,13g,2.4g,61mg,553.00 mg,66.1 mg,10.00 mcg,0.00 mcg,3.590 mg,...,12.68 g,2.422 g,3.474 g,6.086 g,61.00 mg,0.0 g,1.96 g,0.00 mg,0.00 mg,48.43 g
"Babyfood, strained, apple yogurt dessert",100 g,96,1.6g,1g,6mg,20.00 mg,5.4 mg,9.00 mcg,0.00 mcg,0.000 mg,...,1.60 g,1.034 g,0.438 g,0.044 g,6.00 mg,0.0 g,0.20 g,0.00 mg,0.00 mg,77.90 g

In [37]:
# from nutr_mini extract total_fat and cholesterol for all rows
nutr_mini.loc[:,["total_fat","cholesterol"]]  # df.loc[rows,columns]

                                                   total_fat cholesterol
name
Oil, bowhead (Alaska Native), whale                     100g           0
Soup, ready-to-serve, canned, chunky chicken no...      1.2g         5mg
Muffins, oat bran                                       7.4g           0
Turkey, bone removed, with skin, cooked, smoked...       12g        81mg
SMART SOUP, Indian Bean Masala                          0.9g           0
Soup, canned, HEALTHY CHOICE Chicken and Rice Soup      0.6g         7mg
CAMPBELL'S Red and White, condensed, Minestrone...      0.8g         4mg
Lamb, raw, separable lean only, boneless, loin,...      3.8g        66mg
Restaurant, orange chicken, Chinese                      13g        61mg
Babyfood, strained, apple yogurt dessert                1.6g         6mg

In [38]:
# Extract all columns for vitamin_b12 to end, for the first,second,third rows
nutr_mini.iloc[0:3,20:]

,vitamin_b12,vitamin_b6,vitamin_c,vitamin_d,vitamin_e,tocopherol_alpha,vitamin_k,calcium,copper,irom,...,fat,saturated_fatty_acids,monounsaturated_fatty_acids,polyunsaturated_fatty_acids,fatty_acids_total_trans,alcohol,ash,caffeine,theobromine,water
name,,,,,,,,,,,,,,,,,,,,,
"Oil, bowhead (Alaska Native), whale",0,0,0,0,0,0,0,0.00 mg,0,0.00 mg,...,100.00 g,0,0,0,0,0,0.00 g,0,0,0.00 g
"Soup, ready-to-serve, canned, chunky chicken noodle",0.08 mcg,0.050 mg,0.4 mg,0.00 IU,0.12 mg,0.12 mg,1.7 mcg,11.00 mg,0.028 mg,0.35 mg,...,1.16 g,0.627 g,0.298 g,0.172 g,5.00 mg,0.0 g,1.40 g,0.00 mg,0.00 mg,89.88 g
"Muffins, oat bran",0.01 mcg,0.161 mg,0.0 mg,0.00 IU,0.66 mg,0.66 mg,13.0 mcg,63.00 mg,0.330 mg,4.20 mg,...,7.40 g,1.087 g,1.695 g,4.129 g,0.00 mg,0.0 g,2.30 g,0.00 mg,0.00 mg,35.00 g

'100g1.2g7.4g12g0.9g0.6g0.8g3.8g13g1.6g'